wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.8.16
    cli_version: 0.15.0
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1694141509.344706
    t:
      1:
      - 55
      2:
      - 55
      3:
      - 23
      4: 3.8.16
      5: 0.15.0
      8:
      - 1
      - 5
